version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: pg_invoice
    environment:
      POSTGRES_USER: invoice
      POSTGRES_PASSWORD: invoice123
      POSTGRES_DB: invoice_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: invoice_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DSN=host=postgres user=invoice password=invoice123 dbname=invoice_dev sslmode=disable
    volumes:
      - .:/app # hot-reload
    command: >
      sh -c "go mod tidy && air"   # gunakan air untuk hot-reload
volumes:
  pgdata:
